export const sponsorshipStats = {
  combinedFollowers: '1.05M+',
  activePlatforms: '3',
  creatorCount: '6',
};

export const creatorNetwork = [
  {
    name: 'Jake Anilao',
    slug: 'jake-anilao',
    role: 'Brand Ambassador / Basketball Coach',
    contactNumber: '09387841636',
    address: '#59 Calamansi St., Zone C, Brgy. San Miguel, Tarlac City',
    dateOfBirth: '1991-06-16',
    jobDescription: 'Resurgence Powered by DesignXpress Co-Owner, Brand Ambassador, Basketball Coach and Influencer/Vlogger',
    position: '',
    height: '',
    facebookPage: 'https://www.facebook.com/profile.php?id=100086690809185',
    facebookFollowers: '1M followers',
    tiktokPage: '',
    tiktokFollowers: '',
    instagramPage: '',
    instagramFollowers: '',
    youtubePage: 'https://www.youtube.com/@jakeanilao3861',
    youtubeFollowers: '5.64K subscribers',
    trendingVideoUrl: 'https://www.facebook.com/reel/734220602866816',
    platformFocus: 'Basketball leadership, sponsorship storytelling, coaching, and creator-led brand visibility.',
    audience: 'High-trust sports and grassroots basketball community reach across Facebook and YouTube.',
    biography: 'Jake leads RESURGENCE as a co-owner, coach, brand ambassador, and on-camera creator who connects sponsor storytelling with real basketball communities.',
    shortBio: 'Co-owner, basketball coach, brand ambassador, and influencer/vlogger for Resurgence Powered by DesignXpress.',
    journeyStory: 'Jake built his creator presence through basketball leadership, community-first coaching, and sponsor-ready storytelling for the Resurgence ecosystem.',
    pointsPerGame: 18.4,
    assistsPerGame: 7.2,
    reboundsPerGame: 6.1,
    imageUrl: '/assets/jake-image1.jpg',
  },
  {
    name: 'Klinthon S. Almine',
    slug: 'klinthon-s-almine',
    role: 'All Around',
    contactNumber: '09664117353',
    address: 'P-2 Sta. Cruz, San Jose, Dinagat Island',
    dateOfBirth: '1997-07-13',
    jobDescription: 'Basketball Player and Influencer/Vlogger',
    position: 'All Around',
    height: "6'3",
    facebookPage: '',
    facebookFollowers: '',
    tiktokPage: '',
    tiktokFollowers: '',
    instagramPage: '',
    instagramFollowers: '',
    youtubePage: '',
    youtubeFollowers: '',
    trendingVideoUrl: '',
    platformFocus: 'Basketball player content, all-around court presence, and emerging influencer/vlogger storytelling.',
    audience: 'High-potential basketball audience and creator growth segment.',
    biography: 'Klinthon is an all-around basketball player and influencer/vlogger representing the next wave of Resurgence creator talent.',
    shortBio: 'All-around basketball player and influencer/vlogger.',
    journeyStory: 'Klinthon brings size, versatility, and creator potential into the Resurgence network as a rising sports personality.',
    pointsPerGame: 10.4,
    assistsPerGame: 4.4,
    reboundsPerGame: 4.9,
    imageUrl: '/assets/klint-image1.jpg',
  },
  {
    name: 'Joshua Dollente',
    slug: 'joshua-dollente',
    role: 'Shooting Guard',
    contactNumber: '09267206345',
    address: 'Blk 21 Lot 4, St. Therese, Deca Homes, Marilao, Bulacan',
    dateOfBirth: '1997-07-20',
    jobDescription: 'Resurgence Powered by DesignXpress Co-Owner, Basketball Player and Influencer/Vlogger',
    position: 'Shooting Guard',
    height: "5'8",
    facebookPage: 'https://www.facebook.com/joshua.dollente.399421',
    facebookFollowers: '35K followers',
    tiktokPage: '',
    tiktokFollowers: '',
    instagramPage: 'https://www.instagram.com/joshuadollente20',
    instagramFollowers: '32 followers',
    youtubePage: '',
    youtubeFollowers: '',
    trendingVideoUrl: '',
    platformFocus: 'Basketball player content, co-owner storytelling, and sponsor-ready creator visibility.',
    audience: 'Facebook-led basketball audience with supporting Instagram presence.',
    biography: 'Joshua is a Resurgence co-owner, shooting guard, basketball player, and influencer/vlogger with strong creator reach.',
    shortBio: 'Co-owner, shooting guard, basketball player, and influencer/vlogger.',
    journeyStory: 'Joshua combines competitive basketball credibility with creator-led digital storytelling for sponsor and community visibility.',
    pointsPerGame: 14.8,
    assistsPerGame: 4.7,
    reboundsPerGame: 4.2,
    imageUrl: '/assets/joshua-image1.jpg',
  },
  {
    name: 'Gabriel Dimalanta',
    slug: 'gabriel-dimalanta',
    role: 'Small Forward',
    contactNumber: '09153953622',
    address: '20 Don Jose St., Kimco Village, Sauyo, Novaliches, Quezon City',
    dateOfBirth: '2000-04-28',
    jobDescription: 'Resurgence Powered by DesignXpress Co-Owner, Basketball Player and Influencer/Vlogger',
    position: 'Small Forward',
    height: '',
    facebookPage: '',
    facebookFollowers: '',
    tiktokPage: '',
    tiktokFollowers: '',
    instagramPage: '',
    instagramFollowers: '',
    youtubePage: '',
    youtubeFollowers: '',
    trendingVideoUrl: '',
    platformFocus: 'Small forward basketball content, athlete lifestyle, and branded creator integrations.',
    audience: 'Performance-driven basketball viewers and local sports community.',
    biography: 'Gabriel is a Resurgence co-owner, small forward, basketball player, and influencer/vlogger with athlete-led campaign potential.',
    shortBio: 'Co-owner, small forward, basketball player, and influencer/vlogger.',
    journeyStory: 'Gabriel brings competitive basketball experience and creator-athlete storytelling into the Resurgence sponsorship network.',
    pointsPerGame: 16.8,
    assistsPerGame: 4.9,
    reboundsPerGame: 5.3,
    imageUrl: '/assets/gab-image.jpg',
  },
  {
    name: 'Angelo Deciembre',
    slug: 'angelo-deciembre',
    role: 'Power Forward',
    contactNumber: '09295751793',
    address: '26 Don Francisco St., Villa Beatriz, Brgy. Matandang Balara',
    dateOfBirth: '1994-12-16',
    jobDescription: 'Resurgence Powered by DesignXpress Co-Owner, Basketball Player and Influencer/Vlogger',
    position: 'Power Forward',
    height: "5'9",
    facebookPage: '',
    facebookFollowers: '',
    tiktokPage: '',
    tiktokFollowers: '',
    instagramPage: '',
    instagramFollowers: '',
    youtubePage: '',
    youtubeFollowers: '',
    trendingVideoUrl: '',
    platformFocus: 'Power forward basketball content, brand awareness, and partnership storytelling.',
    audience: 'Credibility-based basketball and sports community reach.',
    biography: 'Angelo is a Resurgence co-owner, power forward, basketball player, and influencer/vlogger focused on sports storytelling.',
    shortBio: 'Co-owner, power forward, basketball player, and influencer/vlogger.',
    journeyStory: 'Angelo adds credibility, court presence, and personality-led audience trust across Resurgence campaigns and brand messages.',
    pointsPerGame: 14.1,
    assistsPerGame: 6.0,
    reboundsPerGame: 5.8,
    imageUrl: '/assets/angelo-image1.jpg',
  },
  {
    name: 'Marlon Villamin Facundo',
    slug: 'marlon-villamin-facundo',
    role: 'Point Guard',
    contactNumber: '09675102324',
    address: '35 Jose Abad Santos, Barangay Sta. Lucia, Novaliches, QC',
    dateOfBirth: '1999-07-18',
    jobDescription: 'Resurgence Powered by DesignXpress Co-Owner, Basketball Player and Influencer/Vlogger',
    position: 'Point Guard',
    height: "5'6",
    facebookPage: 'https://www.facebook.com/macol.facundo7',
    facebookFollowers: '12K followers',
    tiktokPage: '',
    tiktokFollowers: '',
    instagramPage: '',
    instagramFollowers: '',
    youtubePage: '',
    youtubeFollowers: '',
    trendingVideoUrl: 'https://www.facebook.com/reel/26628084156811313',
    platformFocus: 'Point guard basketball content, community storytelling, and creator-led promotions.',
    audience: 'Community-first basketball audience with strong Facebook presence.',
    biography: 'Marlon is a Resurgence co-owner, point guard, basketball player, and influencer/vlogger with community-driven reach.',
    shortBio: 'Co-owner, point guard, basketball player, and influencer/vlogger.',
    journeyStory: 'Marlon stays close to local basketball communities and converts grassroots attention into Resurgence event and sponsor energy.',
    pointsPerGame: 13.5,
    assistsPerGame: 5.1,
    reboundsPerGame: 6.7,
    imageUrl: '/assets/macol-image1.jpg',
  },
] as const;

export const sponsorInventoryCategories = [
  {
    name: 'Branding Assets',
    description: 'Jersey placement, event signage, posters, branded merchandise, and physical visibility assets.',
    examples: ['Jersey logo placement', 'Backdrop and LED signage', 'Poster and event collateral'],
  },
  {
    name: 'Digital Integration',
    description: 'Creator-led posts, reels, social mentions, package callouts, and lead-generation content.',
    examples: ['Reels and short-form videos', 'Social posting inclusion', 'Lead capture integrations'],
  },
  {
    name: 'On-Ground Activation',
    description: 'Venue activations, experiential booths, live mentions, and game-day sponsor exposure.',
    examples: ['Booth presence', 'Live acknowledgements', 'Sampling and activation space'],
  },
  {
    name: 'Commercial Support',
    description: 'Proposal customizations, package structuring, brand alignment, and commercial delivery support.',
    examples: ['Tailored proposal support', 'Activation planning', 'Commercial coordination'],
  },
] as const;

export const sponsorPackageTemplates = [
  {
    name: 'Supporting Sponsor',
    tier: 'Supporting Sponsor',
    value: 'PHP 15,000-50,000',
    rangeLabel: 'PHP 15,000-50,000',
    summary: 'Entry sponsorship tier designed for visibility, community support, and targeted activation value.',
    benefits: [
      'Logo placement on selected event and digital assets',
      'Inclusion in sponsor recognition materials',
      'Visibility across select social and event mentions',
      'Access to structured grassroots brand exposure',
    ],
  },
  {
    name: 'Official Brand Partner',
    tier: 'Official Brand Partner',
    value: 'PHP 75,000-95,000',
    rangeLabel: 'PHP 75,000-95,000',
    summary: 'Mid-tier brand partnership with stronger digital integration and broader sponsorship positioning.',
    benefits: [
      'Enhanced brand placement across sponsor-facing materials',
      'Digital integration across creator and campaign assets',
      'Expanded event visibility and partner callouts',
      'Priority inclusion in activation planning',
    ],
  },
  {
    name: 'Major Partner',
    tier: 'Major Partner',
    value: 'PHP 120,000-150,000',
    rangeLabel: 'PHP 120,000-150,000',
    summary: 'High-impact partnership tier for brands seeking premium integration and strong commercial presence.',
    benefits: [
      'Premium logo placement and sponsor positioning',
      'Expanded creator-network integration',
      'On-ground activation prioritization',
      'High-visibility commercial support and packaged deliverables',
    ],
  },
  {
    name: 'Event Presenting',
    tier: 'Event Presenting',
    value: 'Custom Proposal',
    rangeLabel: 'Custom Proposal',
    summary: 'Custom presenting package for lead brands seeking headline integration and tailored sponsorship rights.',
    benefits: [
      'Custom proposal structure based on event or campaign scale',
      'Presenting-level brand integration',
      'Priority negotiation on activations and deck placement',
      'Tailored deliverables, branding, and commercial support',
    ],
  },
] as const;

export const roleMeta = {
  SYSTEM_ADMIN: {
    label: 'System Admin',
    defaultRoute: '/admin',
    accent: '2026 sponsorship operations',
  },
  CASHIER: {
    label: 'Cashier',
    defaultRoute: '/cashier',
    accent: 'billing, receipts, and collections',
  },
  MEMBER: {
    label: 'Regular Member',
    defaultRoute: '/member',
    accent: 'community access, merch, updates, and member benefits',
  },
  SPONSOR: {
    label: 'Sponsor',
    defaultRoute: '/sponsor/dashboard',
    accent: 'package visibility and deliverables',
  },
  STAFF: {
    label: 'Staff',
    defaultRoute: '/staff',
    accent: 'coordination and inquiry workflow',
  },
  PARTNER: {
    label: 'Partner',
    defaultRoute: '/partner',
    accent: 'campaigns, referrals, and agreements',
  },
  CREATOR: {
    label: 'Creator',
    defaultRoute: '/creator/dashboard',
    accent: 'creator profile, social reach, and sponsor readiness',
  },
  COACH: {
    label: 'Coach',
    defaultRoute: '/coach',
    accent: 'training leadership, team development, and event readiness',
  },
  REFEREE: {
    label: 'Referee',
    defaultRoute: '/referee',
    accent: 'officiating profile, game availability, and assignment readiness',
  },
} as const;

export const rolePrefixes = {
  SYSTEM_ADMIN: ['/admin'],
  CASHIER: ['/cashier'],
  MEMBER: ['/member'],
  SPONSOR: ['/sponsor/dashboard', '/sponsor/applications', '/sponsor/packages', '/sponsor/placements', '/sponsor/deliverables', '/sponsor/billing', '/sponsor/profile'],
  STAFF: ['/staff'],
  PARTNER: ['/partner'],
  CREATOR: ['/creator/dashboard', '/creator/posts', '/creator/analytics'],
  COACH: ['/coach'],
  REFEREE: ['/referee'],
} as const;

export type AppRole = keyof typeof roleMeta;
